playwright_test:
	behave --tags=@playwright --format html --out test_artifacts/report/report.html

# Command to run Selenium tests
selenium_test:
	behave --tags=@selenium --format html --out test_artifacts/report/report.html


#python -m pdb -m behave --tags=@playwright --format html --out test_artifacts/report/report.html
